apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  parallelism: 2
  completions: 2
  template:
    spec:
      containers:
      - name: busybox
        image: daniweb87/busybox
        command: ["sleep", "60"]
      restartPolicy: Never
