apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    env:
    - name: PROJECTNAME
      valueFrom:
        configMapKeyRef:
          name: demo-configmap
          key: project.name
    - name: PROJECTDSN
      valueFrom:
        configMapKeyRef:
          name: demo-configmap
          key: DSNurl
