apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: busybox
        image: daniweb87/busybox
        command: ["ls", "/dani"]
      restartPolicy: Never

